# Generated by Django 5.1.3 on 2025-03-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='delivery_return_policy',
        ),
        migrations.AddField(
            model_name='listing',
            name='deliveryTime',
            field=models.CharField(default='5-7 days', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='exchangeEligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='returnEligible',
            field=models.BooleanField(default=False),
        ),
    ]
