# Generated by Django 5.1.3 on 2025-03-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizeguide',
            name='chest',
        ),
        migrations.RemoveField(
            model_name='sizeguide',
            name='hips',
        ),
        migrations.RemoveField(
            model_name='sizeguide',
            name='waist',
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='Accross_Shoulders',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='FrontLength',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='Hip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='Inseam_Length',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='Sleeve_length',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='Chest',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='Waist',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
