# Generated by Django 5.1.3 on 2025-03-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_listing_delivery_return_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bestSelling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='newArrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='specialOffer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
