# Generated by Django 5.1.3 on 2025-03-17 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_listing_bestselling_listing_newarrival_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='color',
            old_name='hex_code',
            new_name='hexCode',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='discounted_price',
            new_name='discountedPrice',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='stock_quantity',
            new_name='stockQuantity',
        ),
        migrations.AddField(
            model_name='listing',
            name='uniqueLabel',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='productType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.producttype'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('productType', 'uniqueLabel'), name='unique_product_label'),
        ),
    ]
