# Generated by Django 5.1.3 on 2025-04-03 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
