# Generated by Django 5.1.3 on 2025-03-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_user_dob_user_firstname_user_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='isfeatured',
            new_name='IsFeatured',
        ),
        migrations.AddField(
            model_name='brand',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
