# Generated by Django 5.1.3 on 2025-03-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
