# Generated by Django 5.1.3 on 2025-03-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_producttype_rename_hex_code_color_hexcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='productDetails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
