# Generated by Django 5.1.3 on 2025-03-30 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_coupon_isactive'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sizeguide',
            unique_together={('brand', 'category', 'size_label')},
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='category',
            field=models.ForeignKey(default='tshirt', on_delete=django.db.models.deletion.CASCADE, related_name='size_guides', to='home.category'),
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='hips',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='size_label',
            field=models.CharField(default='S', max_length=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='sizeguide',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_guides', to='home.brand'),
        ),
        migrations.AlterField(
            model_name='sizeguide',
            name='chest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sizeguide',
            name='waist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='sizeguide',
            name='hip',
        ),
        migrations.RemoveField(
            model_name='sizeguide',
            name='size',
        ),
    ]
