# Generated by Django 5.1.3 on 2025-03-18 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_aboutbrand_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='aboutBrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.aboutbrand'),
        ),
    ]
