# Generated by Django 5.1.3 on 2025-03-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_listing_aboutbrand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='aboutBrand',
        ),
    ]
