# Generated by Django 5.1.3 on 2025-03-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='limitedTime',
            field=models.BooleanField(default=False),
        ),
    ]
