# Generated by Django 5.1.3 on 2025-03-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_listing_limitedtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='stockQuantity',
        ),
    ]
