# Generated by Django 5.1.3 on 2025-03-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_listing_stockquantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('percentage', models.IntegerField()),
                ('minCartValue', models.IntegerField()),
                ('maxDiscount', models.IntegerField()),
            ],
        ),
    ]
