# Generated by Django 5.1.3 on 2025-03-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='isfeatured',
            field=models.BooleanField(default=False),
        ),
    ]
