# Generated by Django 5.1.3 on 2025-03-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_brand_isfeatured'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AboutBrand',
        ),
    ]
